<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <ApplicationIcon>..\..\assets\DeskSwipe.ico</ApplicationIcon>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>DeskSwipe.Settings</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>

		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>

		<WindowsPackageType>None</WindowsPackageType>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

		<EnableMsixTooling>false</EnableMsixTooling>

		<Nullable>enable</Nullable>

  </PropertyGroup>

	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\StoreLogo.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeskSwipe.Settings.Core\DeskSwipe.Settings.Core.csproj" />
	</ItemGroup>

	<PropertyGroup>
    <ApplicationIcon>..\..\assets\DeskSwipe.ico</ApplicationIcon>


    <PublishTrimmed>False</PublishTrimmed>

  </PropertyGroup>
</Project>







